/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	edgev1alpha1 "github.com/ohmk/k8s-edge/pkg/apis/edge/v1alpha1"
	versioned "github.com/ohmk/k8s-edge/pkg/client/clientset/versioned"
	internalinterfaces "github.com/ohmk/k8s-edge/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/ohmk/k8s-edge/pkg/client/listers/edge/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EdgeNodeInformer provides access to a shared informer and lister for
// EdgeNodes.
type EdgeNodeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.EdgeNodeLister
}

type edgeNodeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewEdgeNodeInformer constructs a new informer for EdgeNode type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEdgeNodeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEdgeNodeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredEdgeNodeInformer constructs a new informer for EdgeNode type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEdgeNodeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EdgeV1alpha1().EdgeNodes(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EdgeV1alpha1().EdgeNodes(namespace).Watch(options)
			},
		},
		&edgev1alpha1.EdgeNode{},
		resyncPeriod,
		indexers,
	)
}

func (f *edgeNodeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEdgeNodeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *edgeNodeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&edgev1alpha1.EdgeNode{}, f.defaultInformer)
}

func (f *edgeNodeInformer) Lister() v1alpha1.EdgeNodeLister {
	return v1alpha1.NewEdgeNodeLister(f.Informer().GetIndexer())
}
