/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/ohmk/k8s-edge/pkg/apis/edge/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEdgeNodes implements EdgeNodeInterface
type FakeEdgeNodes struct {
	Fake *FakeEdgeV1alpha1
	ns   string
}

var edgenodesResource = schema.GroupVersionResource{Group: "edge.k8s.io", Version: "v1alpha1", Resource: "edgenodes"}

var edgenodesKind = schema.GroupVersionKind{Group: "edge.k8s.io", Version: "v1alpha1", Kind: "EdgeNode"}

// Get takes name of the edgeNode, and returns the corresponding edgeNode object, and an error if there is any.
func (c *FakeEdgeNodes) Get(name string, options v1.GetOptions) (result *v1alpha1.EdgeNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(edgenodesResource, c.ns, name), &v1alpha1.EdgeNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EdgeNode), err
}

// List takes label and field selectors, and returns the list of EdgeNodes that match those selectors.
func (c *FakeEdgeNodes) List(opts v1.ListOptions) (result *v1alpha1.EdgeNodeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(edgenodesResource, edgenodesKind, c.ns, opts), &v1alpha1.EdgeNodeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.EdgeNodeList{ListMeta: obj.(*v1alpha1.EdgeNodeList).ListMeta}
	for _, item := range obj.(*v1alpha1.EdgeNodeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested edgeNodes.
func (c *FakeEdgeNodes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(edgenodesResource, c.ns, opts))

}

// Create takes the representation of a edgeNode and creates it.  Returns the server's representation of the edgeNode, and an error, if there is any.
func (c *FakeEdgeNodes) Create(edgeNode *v1alpha1.EdgeNode) (result *v1alpha1.EdgeNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(edgenodesResource, c.ns, edgeNode), &v1alpha1.EdgeNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EdgeNode), err
}

// Update takes the representation of a edgeNode and updates it. Returns the server's representation of the edgeNode, and an error, if there is any.
func (c *FakeEdgeNodes) Update(edgeNode *v1alpha1.EdgeNode) (result *v1alpha1.EdgeNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(edgenodesResource, c.ns, edgeNode), &v1alpha1.EdgeNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EdgeNode), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEdgeNodes) UpdateStatus(edgeNode *v1alpha1.EdgeNode) (*v1alpha1.EdgeNode, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(edgenodesResource, "status", c.ns, edgeNode), &v1alpha1.EdgeNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EdgeNode), err
}

// Delete takes name of the edgeNode and deletes it. Returns an error if one occurs.
func (c *FakeEdgeNodes) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(edgenodesResource, c.ns, name), &v1alpha1.EdgeNode{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEdgeNodes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(edgenodesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.EdgeNodeList{})
	return err
}

// Patch applies the patch and returns the patched edgeNode.
func (c *FakeEdgeNodes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.EdgeNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(edgenodesResource, c.ns, name, pt, data, subresources...), &v1alpha1.EdgeNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EdgeNode), err
}
